[package]
name = "nlogger"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
log = { version = "0.4.28", features = ["std", "kv_unstable"] }
rustler = "0.37.0"
once_cell = "1.19"
